### ISSUE TITLE
Weird failures for "dogs of war_maberry_FINALMS_92916.docx"

### ISSUE THREAD

**Issue by nelliemckesson** [macmillanpublishers/bookmaker_validator#62]
"dogs of war_maberry_FINALMS_92916.docx" is getting some ISBN failures, even though there are ISBNs present in the manuscript. It looks like a macro is failing for some reason. I tested re-running conversion with the ISBN in the filename, and it failed again. See log files for more info:

Original file: 
Dropbox/bookmaker_logs/bookmaker_validator/logs/dogsofwar_maberry_FINALMS_92916__2016-10-17_09-38-59

Resubmitted file: 
Dropbox/bookmaker_logs/bookmaker_validator/logs/dogsofwar_maberry_FINALMS_92916_9781250098481__2016-10-17_09-53-25

**Comment by ericawarren** [comment]
@mattretzer @nelliemckesson the Word file is password protected, which locks track changes (so the macro errored when trying to toggle that property). I'll add an additional check for doc protection, and if the file is protected we can send an email to the submitted *AND* the PE, since it is generally the PE who adds this (so the author is forced to make tracked edits). What is the best way to pass that info back to the validator? It looks like it failed in ISBNSearch, so I can add an additional item to the JSON returned by that macro. Maybe, if `"pass":False` check for `"protected":True` ?
